# Ansible Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Playbook execution
alias ap='ansible-playbook'
alias apc='ansible-playbook --check'
alias apd='ansible-playbook --diff'
alias apcd='ansible-playbook --check --diff'
alias apv='ansible-playbook -v'
alias apvv='ansible-playbook -vv'
alias apvvv='ansible-playbook -vvv'

# Inventory
alias ai='ansible-inventory'
alias ail='ansible-inventory --list'
alias aig='ansible-inventory --graph'

# Ad-hoc commands
alias a='ansible'
alias aping='ansible all -m ping'
alias afacts='ansible all -m setup'

# Vault
alias av='ansible-vault'
alias ave='ansible-vault encrypt'
alias avd='ansible-vault decrypt'
alias avv='ansible-vault view'
alias aved='ansible-vault edit'

# Galaxy
alias ag='ansible-galaxy'
alias agi='ansible-galaxy install'
alias agir='ansible-galaxy install -r requirements.yml'
alias agl='ansible-galaxy list'

# Config & docs
alias aconfig='ansible-config'
alias adoc='ansible-doc'

# Lint
alias alint='ansible-lint'
