# AWS CLI Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# AWS profile management
alias aws-whoami='aws sts get-caller-identity'
alias aws-profiles='cat ~/.aws/credentials | grep "\[" | tr -d "[]"'
alias aws-regions='aws ec2 describe-regions --query "Regions[].RegionName" --output table'

# AWS profile switching function
aws-profile() {
    if [[ -z "$1" ]]; then
        echo "Current: ${AWS_PROFILE:-default}"
        echo "Available profiles:"
        aws-profiles
    else
        export AWS_PROFILE="$1"
        echo "Switched to profile: $1"
    fi
}

# EC2 shortcuts
alias ec2-list='aws ec2 describe-instances --query "Reservations[].Instances[].[InstanceId,State.Name,Tags[?Key==\`Name\`].Value|[0]]" --output table'
alias ec2-running='aws ec2 describe-instances --filters "Name=instance-state-name,Values=running" --query "Reservations[].Instances[].[InstanceId,Tags[?Key==\`Name\`].Value|[0]]" --output table'

# S3 shortcuts
alias s3-ls='aws s3 ls'
alias s3-buckets='aws s3api list-buckets --query "Buckets[].Name" --output table'

# Lambda shortcuts
alias lambda-list='aws lambda list-functions --query "Functions[].FunctionName" --output table'

# CloudFormation shortcuts
alias cfn-stacks='aws cloudformation list-stacks --query "StackSummaries[?StackStatus!=\`DELETE_COMPLETE\`].[StackName,StackStatus]" --output table'
