# Azure CLI Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Auth & account
alias az-login='az login'
alias az-logout='az logout'
alias az-account='az account show'
alias az-accounts='az account list --output table'
alias az-subs='az account subscription list --output table'

# Subscription switching
az-use() {
    az account set --subscription "$1"
    echo "Switched to subscription: $1"
}

# Resource groups
alias az-rg='az group list --output table'
alias az-rgcreate='az group create'
alias az-rgdelete='az group delete'

# Virtual Machines
alias az-vms='az vm list --output table'
alias az-vmstart='az vm start'
alias az-vmstop='az vm stop'
alias az-vmrestart='az vm restart'
alias az-vmssh='az ssh vm'

# Storage
alias az-storage='az storage account list --output table'
alias az-containers='az storage container list --output table'
alias az-blobs='az storage blob list --output table'

# AKS (Kubernetes)
alias az-aks='az aks list --output table'
alias az-akscreds='az aks get-credentials'
alias az-aksstart='az aks start'
alias az-aksstop='az aks stop'

# App Service
alias az-apps='az webapp list --output table'
alias az-appstart='az webapp start'
alias az-appstop='az webapp stop'
alias az-apprestart='az webapp restart'

# Functions
alias az-func='az functionapp list --output table'

# Container Registry
alias az-acr='az acr list --output table'
alias az-acrlogin='az acr login'

# Key Vault
alias az-kv='az keyvault list --output table'
alias az-kvsecrets='az keyvault secret list'

# Info
alias az-version='az version'
alias az-regions='az account list-locations --output table'
