# Directory Shortcuts (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Common directories
alias ~='cd ~'
alias ..='cd ..'
alias ...='cd ../..'
alias ....='cd ../../..'
alias .....='cd ../../../..'

# Home subdirectories
alias dl='cd ~/Downloads'
alias docs='cd ~/Documents'
alias dt='cd ~/Desktop'
alias proj='cd ~/Projects 2>/dev/null || cd ~/projects 2>/dev/null || echo "Projects folder not found"'
alias repos='cd ~/repos 2>/dev/null || cd ~/Repos 2>/dev/null || cd ~/Projects 2>/dev/null || echo "Repos folder not found"'

# Quick mkdir and cd
mkcd() {
    mkdir -p "$1" && cd "$1"
}

# Go back to previous directory
alias bd='cd -'

# List directory shortcuts
alias l='ls -lah'
alias ll='ls -lh'
alias la='ls -la'
alias lt='ls -lahtr'

# Tree shortcuts (if installed)
alias tree1='tree -L 1'
alias tree2='tree -L 2'
alias tree3='tree -L 3'

# Find in current directory
alias ff='find . -name'
alias fdir='find . -type d -name'
alias ffile='find . -type f -name'

# Quick path copy
pwdc() {
    pwd | tr -d '\n' | pbcopy 2>/dev/null || pwd | tr -d '\n' | xclip -selection clipboard 2>/dev/null || pwd
    echo "Path copied: $(pwd)"
}

# Bookmark system
BOOKMARKS_FILE="$HOME/.zsh_bookmarks"

bookmark() {
    local name="${1:-$(basename $(pwd))}"
    echo "$name=$(pwd)" >> "$BOOKMARKS_FILE"
    echo "Bookmarked: $name -> $(pwd)"
}

goto() {
    if [[ -f "$BOOKMARKS_FILE" ]]; then
        local path=$(grep "^$1=" "$BOOKMARKS_FILE" | cut -d= -f2)
        if [[ -n "$path" ]]; then
            cd "$path"
        else
            echo "Bookmark not found: $1"
        fi
    fi
}

bookmarks() {
    [[ -f "$BOOKMARKS_FILE" ]] && cat "$BOOKMARKS_FILE" || echo "No bookmarks"
}
