# Docker Compose Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Basic commands
alias dcu='docker compose up'
alias dcud='docker compose up -d'
alias dcd='docker compose down'
alias dcdv='docker compose down -v'
alias dcr='docker compose restart'
alias dcb='docker compose build'
alias dcbn='docker compose build --no-cache'

# Logs & status
alias dcl='docker compose logs'
alias dclf='docker compose logs -f'
alias dcps='docker compose ps'
alias dctop='docker compose top'

# Execute commands
alias dcexec='docker compose exec'
alias dcrun='docker compose run --rm'

# Pull & push
alias dcpull='docker compose pull'
alias dcpush='docker compose push'

# Start & stop
alias dcstart='docker compose start'
alias dcstop='docker compose stop'

# Config validation
alias dcconfig='docker compose config'

# Cleanup
alias dcprune='docker system prune -af'
alias dcclean='docker compose down -v --rmi all'

# Quick rebuild and up
dcrebuild() {
    docker compose down
    docker compose build --no-cache
    docker compose up -d
}
