# Dotenv Loader (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Load .env file manually
dotenv() {
    local envfile="${1:-.env}"
    if [[ -f "$envfile" ]]; then
        set -a
        source "$envfile"
        set +a
        echo "Loaded: $envfile"
    else
        echo "File not found: $envfile"
    fi
}

# Unload .env variables
dotenv-unload() {
    local envfile="${1:-.env}"
    if [[ -f "$envfile" ]]; then
        while IFS= read -r line || [[ -n "$line" ]]; do
            [[ "$line" =~ ^#.*$ ]] && continue
            [[ -z "$line" ]] && continue
            local key="${line%%=*}"
            unset "$key"
        done < "$envfile"
        echo "Unloaded: $envfile"
    fi
}

# Show current .env variables
dotenv-show() {
    local envfile="${1:-.env}"
    if [[ -f "$envfile" ]]; then
        echo "Variables in $envfile:"
        grep -v '^#' "$envfile" | grep -v '^$'
    else
        echo "File not found: $envfile"
    fi
}

# Auto-load .env on directory change (optional - enable with: DOTENV_AUTO=1)
_dotenv_auto_load() {
    [[ "$DOTENV_AUTO" != "1" ]] && return
    [[ -f .env ]] && dotenv
}
chpwd_functions+=(_dotenv_auto_load)

alias env-load='dotenv'
alias env-show='dotenv-show'
alias env-unload='dotenv-unload'
