# Elasticsearch Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Elasticsearch service management
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias es-start='brew services start elasticsearch'
    alias es-stop='brew services stop elasticsearch'
    alias es-restart='brew services restart elasticsearch'
    alias es-status='brew services info elasticsearch'
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    alias es-start='sudo systemctl start elasticsearch'
    alias es-stop='sudo systemctl stop elasticsearch'
    alias es-restart='sudo systemctl restart elasticsearch'
    alias es-status='systemctl status elasticsearch'
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    alias es-start='net start elasticsearch'
    alias es-stop='net stop elasticsearch'
    alias es-restart='net stop elasticsearch & net start elasticsearch'
    alias es-status='sc query elasticsearch'
fi

# Elasticsearch API shortcuts
alias es-health='curl -s localhost:9200/_cluster/health?pretty'
alias es-nodes='curl -s localhost:9200/_cat/nodes?v'
alias es-indices='curl -s localhost:9200/_cat/indices?v'
alias es-shards='curl -s localhost:9200/_cat/shards?v'
alias es-info='curl -s localhost:9200'
