# Extract Plugin - Universal Archive Extraction (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Universal extract function
extract() {
    if [[ -z "$1" ]]; then
        echo "Usage: extract <archive>"
        return 1
    fi
    
    if [[ ! -f "$1" ]]; then
        echo "File not found: $1"
        return 1
    fi
    
    case "$1" in
        *.tar.bz2)   tar xjf "$1"     ;;
        *.tar.gz)    tar xzf "$1"     ;;
        *.tar.xz)    tar xJf "$1"     ;;
        *.tar.zst)   tar --zstd -xf "$1" ;;
        *.bz2)       bunzip2 "$1"     ;;
        *.rar)       unrar x "$1"     ;;
        *.gz)        gunzip "$1"      ;;
        *.tar)       tar xf "$1"      ;;
        *.tbz2)      tar xjf "$1"     ;;
        *.tgz)       tar xzf "$1"     ;;
        *.zip)       unzip "$1"       ;;
        *.Z)         uncompress "$1"  ;;
        *.7z)        7z x "$1"        ;;
        *.xz)        xz -d "$1"       ;;
        *.zst)       zstd -d "$1"     ;;
        *.deb)       ar x "$1"        ;;
        *.rpm)       rpm2cpio "$1" | cpio -idmv ;;
        *)           echo "Unknown archive format: $1" ;;
    esac
}

# Create archives
mktar() { tar cvf  "${1%%/}.tar"     "${1%%/}/"; }
mktgz() { tar cvzf "${1%%/}.tar.gz"  "${1%%/}/"; }
mktbz() { tar cvjf "${1%%/}.tar.bz2" "${1%%/}/"; }
mkzip() { zip -r   "${1%%/}.zip"     "${1%%/}/"; }
mk7z()  { 7z a     "${1%%/}.7z"      "${1%%/}/"; }

# List archive contents without extracting
lstar()  { tar tvf "$1"; }
lszip()  { unzip -l "$1"; }
ls7z()   { 7z l "$1"; }
lsrar()  { unrar l "$1"; }

alias x='extract'
