# Fastlane Mobile CI/CD Aliases (iOS & Android)
# Auto-generated by awesome-lazy-zsh

# ===== Fastlane Core =====
alias fl='fastlane'
alias flv='fastlane --version'
alias flhelp='fastlane --help'
alias flinit='fastlane init'
alias flenv='fastlane env'
alias fldocs='fastlane docs'
alias flupdate='fastlane update_fastlane'
alias flactions='fastlane actions'
alias flaction='fastlane action'
alias flsearch='fastlane search_plugins'
alias flnew='fastlane new_action'

# ===== Lane Execution =====
alias flios='fastlane ios'
alias fland='fastlane android'
alias flbeta='fastlane beta'
alias flrelease='fastlane release'
alias fldeploy='fastlane deploy'
alias fltest='fastlane test'
alias flbuild='fastlane build'
alias fllint='fastlane lint'

# ===== iOS Specific Lanes =====
alias fliosbeta='fastlane ios beta'
alias fliosrelease='fastlane ios release'
alias fliostest='fastlane ios test'
alias fliosbuild='fastlane ios build'
alias flioscerts='fastlane ios certificates'
alias fliosprofiles='fastlane ios profiles'
alias fliospush='fastlane ios push'
alias fliosscreenshots='fastlane ios screenshots'

# ===== Android Specific Lanes =====
alias flandbeta='fastlane android beta'
alias flandrelease='fastlane android release'
alias flandtest='fastlane android test'
alias flandbuild='fastlane android build'
alias flandplaystore='fastlane android playstore'
alias flandinternal='fastlane android internal'
alias flandalpha='fastlane android alpha'

# ===== match (Code Signing) =====
alias flmatch='fastlane match'
alias flmatchdev='fastlane match development'
alias flmatchadhoc='fastlane match adhoc'
alias flmatchapp='fastlane match appstore'
alias flmatchent='fastlane match enterprise'
alias flmatchnuke='fastlane match nuke'
alias flmatchnukedev='fastlane match nuke development'
alias flmatchnukedist='fastlane match nuke distribution'
alias flmatchimport='fastlane match import'
alias flmatchchange='fastlane match change_password'
alias flmatchreadonly='fastlane match --readonly'

# ===== cert & sigh (Manual Signing) =====
alias flcert='fastlane cert'
alias flcertdev='fastlane cert --development'
alias flsigh='fastlane sigh'
alias flsighdev='fastlane sigh --development'
alias flsighadhoc='fastlane sigh --adhoc'
alias flsighapp='fastlane sigh --appstore'
alias flsighrenew='fastlane sigh renew'
alias flsighrepair='fastlane sigh repair'

# ===== gym (Build iOS) =====
alias flgym='fastlane gym'
alias flgymr='fastlane gym --configuration Release'
alias flgymd='fastlane gym --configuration Debug'
alias flgymsilent='fastlane gym --silent'
alias flgymclean='fastlane gym --clean'
alias flgymexport='fastlane gym --export_method'
alias flgymappstore='fastlane gym --export_method app-store'
alias flgymadhoc='fastlane gym --export_method ad-hoc'
alias flgymdev='fastlane gym --export_method development'

# ===== pilot (TestFlight) =====
alias flpilot='fastlane pilot'
alias flpilotup='fastlane pilot upload'
alias flpilotlist='fastlane pilot list'
alias flpilotbuilds='fastlane pilot builds'
alias flpilotadd='fastlane pilot add'
alias flpilotremove='fastlane pilot remove'
alias flpilotexport='fastlane pilot export'
alias flpilotimport='fastlane pilot import'

# ===== deliver (App Store) =====
alias fldeliver='fastlane deliver'
alias fldeliverup='fastlane deliver --submit_for_review'
alias fldeliveronly='fastlane deliver --skip_binary_upload'
alias fldelivermeta='fastlane deliver --skip_screenshots --skip_metadata false'
alias fldeliverscreen='fastlane deliver --skip_metadata --skip_screenshots false'
alias fldeliverforce='fastlane deliver --force'
alias fldeliverdownload='fastlane deliver download_metadata'
alias fldeliverscreens='fastlane deliver download_screenshots'

# ===== supply (Google Play) =====
alias flsupply='fastlane supply'
alias flsupplyup='fastlane supply --track production'
alias flsupplybeta='fastlane supply --track beta'
alias flsupplyalpha='fastlane supply --track alpha'
alias flsupplyinternal='fastlane supply --track internal'
alias flsupplymeta='fastlane supply --skip_upload_apk --skip_upload_aab'
alias flsupplyinit='fastlane supply init'

# ===== snapshot (Screenshots) =====
alias flsnap='fastlane snapshot'
alias flsnapreset='fastlane snapshot reset_simulators'
alias flsnapupdate='fastlane snapshot update'
alias flsnapinit='fastlane snapshot init'

# ===== frameit (Frame Screenshots) =====
alias flframe='fastlane frameit'
alias flframesilver='fastlane frameit silver'
alias flframegold='fastlane frameit gold'
alias flframerose='fastlane frameit rose_gold'

# ===== scan (Testing) =====
alias flscan='fastlane scan'
alias flscandevice='fastlane scan --device'
alias flscanclean='fastlane scan --clean'
alias flscancode='fastlane scan --code_coverage'
alias flscanfail='fastlane scan --fail_build false'
alias flscanoutput='fastlane scan --output_directory'

# ===== gradle (Android Build) =====
alias flgradle='fastlane gradle'
alias flgradleassemble='fastlane gradle task:assemble'
alias flgradletest='fastlane gradle task:test'
alias flgradleclean='fastlane gradle task:clean'
alias flgradlebundle='fastlane gradle task:bundle'

# ===== precheck (App Store Guidelines) =====
alias flprecheck='fastlane precheck'

# ===== pem (Push Notifications) =====
alias flpem='fastlane pem'
alias flpemdev='fastlane pem --development'
alias flpemgen='fastlane pem --generate_p12'
alias flpemsave='fastlane pem --save_private_key'

# ===== spaceship (Apple API) =====
alias flspace='fastlane spaceship'
alias flspacelogin='fastlane spaceauth'

# ===== Plugins =====
alias flplugins='fastlane list_plugins'
alias flpluginsearch='fastlane search_plugins'
alias flpluginadd='fastlane add_plugin'
alias flpluginupdate='fastlane update_plugins'
alias flpluginremove='fastlane remove_plugin'

# ===== Useful Functions =====

# Initialize fastlane for iOS project
function flinitios() {
    if [[ ! -d "ios" ]] && [[ ! -f "*.xcworkspace" ]] && [[ ! -f "*.xcodeproj" ]]; then
        echo "No iOS project found in current directory"
        return 1
    fi
    cd ios 2>/dev/null || true
    fastlane init
}

# Initialize fastlane for Android project
function flinitand() {
    if [[ ! -d "android" ]] && [[ ! -f "build.gradle" ]]; then
        echo "No Android project found in current directory"
        return 1
    fi
    cd android 2>/dev/null || true
    fastlane init
}

# Quick beta release for iOS
function flquickbeta() {
    echo "Building and uploading to TestFlight..."
    fastlane gym --configuration Release --export_method app-store && \
    fastlane pilot upload
}

# Quick beta release for Android
function flandquickbeta() {
    echo "Building and uploading to Play Store internal track..."
    cd android 2>/dev/null || true
    fastlane supply --track internal --aab app/build/outputs/bundle/release/*.aab
}

# Setup match for a new project
function flmatchsetup() {
    echo "Setting up match..."
    echo "Make sure you have:"
    echo "1. A private git repo for certificates"
    echo "2. Apple Developer account access"
    echo ""
    fastlane match init
}

# Renew all certificates and profiles
function flmatchrenew() {
    echo "Renewing all certificates and profiles..."
    fastlane match development --force
    fastlane match adhoc --force
    fastlane match appstore --force
}

# Full iOS release workflow
function fliosfulldeploy() {
    echo "Starting full iOS deployment..."
    echo "1. Running tests..."
    fastlane scan || return 1
    echo "2. Building release..."
    fastlane gym --configuration Release --export_method app-store || return 1
    echo "3. Uploading to TestFlight..."
    fastlane pilot upload || return 1
    echo "4. Submitting for review..."
    fastlane deliver --submit_for_review --automatic_release
    echo "Deployment complete!"
}

# Show all available lanes
function fllanes() {
    if [[ -f "fastlane/Fastfile" ]]; then
        grep -E "^[[:space:]]*(desc|lane)" fastlane/Fastfile | \
        awk '/desc/{desc=$0; next} /lane/{print $0 " - " desc; desc=""}'
    else
        echo "No Fastfile found"
    fi
}

# Create .env file for fastlane
function flenvsetup() {
    local envfile="fastlane/.env"
    if [[ -f "$envfile" ]]; then
        echo "Env file already exists: $envfile"
        return 1
    fi
    cat > "$envfile" << 'EOF'
# Fastlane Environment Variables
# Copy to .env.default and fill in values

# Apple
FASTLANE_USER=your@email.com
FASTLANE_APPLE_APPLICATION_SPECIFIC_PASSWORD=xxxx-xxxx-xxxx-xxxx
MATCH_PASSWORD=your_match_password
MATCH_GIT_URL=git@github.com:your/certificates.git

# App Store Connect API (recommended over password auth)
APP_STORE_CONNECT_API_KEY_ID=XXXXXXXXXX
APP_STORE_CONNECT_API_ISSUER_ID=xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx
APP_STORE_CONNECT_API_KEY_PATH=./AuthKey_XXXXXXXXXX.p8

# Google Play
SUPPLY_JSON_KEY=./google-play-key.json

# Slack notifications (optional)
SLACK_URL=https://hooks.slack.com/services/xxx/xxx/xxx
EOF
    echo "Created $envfile - fill in your values"
    echo "Add to .gitignore: fastlane/.env"
}
