# Firebase CLI Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# ===== Firebase CLI Core =====
alias fb='firebase'
alias fbv='firebase --version'
alias fbhelp='firebase --help'
alias fblogin='firebase login'
alias fbloginci='firebase login:ci'
alias fblogout='firebase logout'
alias fblist='firebase projects:list'
alias fbuse='firebase use'
alias fbinit='firebase init'
alias fbopen='firebase open'
alias fbserve='firebase serve'
alias fbdeploy='firebase deploy'

# ===== Project Management =====
alias fbprojects='firebase projects:list'
alias fbcreate='firebase projects:create'
alias fbaddapp='firebase apps:create'
alias fbapps='firebase apps:list'
alias fbsdkconfig='firebase apps:sdkconfig'
alias fbconfig='firebase functions:config:get'
alias fbconfigset='firebase functions:config:set'
alias fbconfigunset='firebase functions:config:unset'

# ===== Firebase Hosting =====
alias fbhost='firebase deploy --only hosting'
alias fbhostserve='firebase serve --only hosting'
alias fbhostdisable='firebase hosting:disable'
alias fbhostclone='firebase hosting:clone'
alias fbhostchannel='firebase hosting:channel:create'
alias fbhostchannels='firebase hosting:channel:list'
alias fbhostchanneldel='firebase hosting:channel:delete'
alias fbhostpreview='firebase hosting:channel:deploy'
alias fbhostsites='firebase hosting:sites:list'
alias fbhostcreate='firebase hosting:sites:create'
alias fbhostdelete='firebase hosting:sites:delete'

# ===== Cloud Functions =====
alias fbfunc='firebase deploy --only functions'
alias fbfuncserve='firebase serve --only functions'
alias fbfunclogs='firebase functions:log'
alias fbfuncshell='firebase functions:shell'
alias fbfuncdelete='firebase functions:delete'
alias fbfuncsecrets='firebase functions:secrets:access'
alias fbfuncsecretset='firebase functions:secrets:set'
alias fbfuncsecretdel='firebase functions:secrets:destroy'

# ===== Firestore =====
alias fbfs='firebase deploy --only firestore'
alias fbfsrules='firebase deploy --only firestore:rules'
alias fbfsindexes='firebase deploy --only firestore:indexes'
alias fbfsexport='firebase firestore:delete --all-collections'
alias fbfsimport='firebase firestore:import'

# ===== Realtime Database =====
alias fbdb='firebase deploy --only database'
alias fbdbrules='firebase database:rules:get'
alias fbdbpush='firebase database:push'
alias fbdbset='firebase database:set'
alias fbdbget='firebase database:get'
alias fbdbremove='firebase database:remove'
alias fbdbupdate='firebase database:update'
alias fbdbprofile='firebase database:profile'

# ===== Storage =====
alias fbstorage='firebase deploy --only storage'
alias fbstoragerules='firebase deploy --only storage:rules'

# ===== Authentication =====
alias fbauth='firebase auth:export'
alias fbauthimport='firebase auth:import'

# ===== Remote Config =====
alias fbrc='firebase remoteconfig:get'
alias fbrcversions='firebase remoteconfig:versions:list'
alias fbrcrollback='firebase remoteconfig:rollback'

# ===== App Distribution =====
alias fbappdist='firebase appdistribution:distribute'
alias fbappdisttesters='firebase appdistribution:testers:add'
alias fbappdistgroups='firebase appdistribution:group:create'

# ===== Extensions =====
alias fbext='firebase ext'
alias fbextlist='firebase ext:list'
alias fbextinstall='firebase ext:install'
alias fbextupdate='firebase ext:update'
alias fbextuninstall='firebase ext:uninstall'
alias fbextinfo='firebase ext:info'
alias fbextconfigure='firebase ext:configure'
alias fbextsources='firebase ext:sources:create'

# ===== Emulators =====
alias fbemu='firebase emulators:start'
alias fbemuall='firebase emulators:start --import=./emulator-data --export-on-exit'
alias fbemuonly='firebase emulators:start --only'
alias fbemuauth='firebase emulators:start --only auth'
alias fbemufs='firebase emulators:start --only firestore'
alias fbemudb='firebase emulators:start --only database'
alias fbemufunc='firebase emulators:start --only functions'
alias fbemuhost='firebase emulators:start --only hosting'
alias fbemupubsub='firebase emulators:start --only pubsub'
alias fbemustorage='firebase emulators:start --only storage'
alias fbemuexport='firebase emulators:export ./emulator-data'
alias fbemuexec='firebase emulators:exec'
alias fbemuui='firebase emulators:start --ui'

# ===== Testing =====
alias fbtest='firebase test:android:run'
alias fbtestios='firebase test:ios:run'
alias fbtestmodels='firebase test:android:models:list'
alias fbtestiosmodels='firebase test:ios:models:list'

# ===== Crashlytics =====
alias fbcrash='firebase crashlytics:symbols:upload'
alias fbcrashmap='firebase crashlytics:mappingfile:upload'

# ===== Performance Monitoring =====
alias fbperf='firebase perf:config:get'
alias fbperfset='firebase perf:config:update'

# ===== Analytics =====
# Note: Analytics is primarily managed via Console, limited CLI support

# ===== Cloud Messaging =====
# Note: FCM is primarily managed via Console/SDK

# ===== Deploy Shortcuts =====
alias fbdeployall='firebase deploy'
alias fbdeployhost='firebase deploy --only hosting'
alias fbdeployfunc='firebase deploy --only functions'
alias fbdeployfs='firebase deploy --only firestore'
alias fbdeploydb='firebase deploy --only database'
alias fbdeploystorage='firebase deploy --only storage'
alias fbdeployrules='firebase deploy --only firestore:rules,storage:rules,database'
alias fbdeploypreview='firebase hosting:channel:deploy preview'

# ===== Useful Functions =====

# Initialize Firebase for a new project
function fbsetup() {
    echo "Setting up Firebase project..."
    echo "Select the features you want to set up:"
    firebase init
}

# Quick deploy with message
function fbdeploymsg() {
    if [[ -z "$1" ]]; then
        echo "Usage: fbdeploymsg <message>"
        return 1
    fi
    echo "Deploying: $1"
    firebase deploy -m "$1"
}

# Start emulators with data persistence
function fbemudata() {
    local datadir="${1:-./emulator-data}"
    firebase emulators:start --import="$datadir" --export-on-exit="$datadir"
}

# Deploy only specific function(s)
function fbfuncdeploy() {
    if [[ -z "$1" ]]; then
        echo "Usage: fbfuncdeploy <function_name> [function_name2...]"
        return 1
    fi
    local funcs=$(echo "$@" | tr ' ' ',')
    firebase deploy --only "functions:$funcs"
}

# View function logs with follow
function fbfunclogsf() {
    local func="${1:-}"
    if [[ -n "$func" ]]; then
        firebase functions:log --only "$func" -f
    else
        firebase functions:log -f
    fi
}

# Switch Firebase project
function fbswitch() {
    if [[ -z "$1" ]]; then
        echo "Available projects:"
        firebase projects:list
        echo ""
        echo "Usage: fbswitch <project_id_or_alias>"
        return 1
    fi
    firebase use "$1"
}

# Setup Firebase emulators with all services
function fbemusetup() {
    firebase init emulators
}

# Export Firestore data
function fbfsbackup() {
    local bucket="${1:-}"
    if [[ -z "$bucket" ]]; then
        echo "Usage: fbfsbackup <gcs_bucket_name>"
        return 1
    fi
    gcloud firestore export "gs://$bucket/$(date +%Y%m%d-%H%M%S)"
}

# Deploy to preview channel and get URL
function fbpreview() {
    local channel="${1:-preview}"
    firebase hosting:channel:deploy "$channel" && \
    echo "\nPreview URL:" && \
    firebase hosting:channel:list | grep "$channel"
}

# Run functions locally with emulator
function fbfunclocal() {
    firebase emulators:start --only functions --inspect-functions
}

# Full local development setup
function fbdevstart() {
    echo "Starting Firebase local development..."
    echo "Emulator UI: http://localhost:4000"
    firebase emulators:start --import=./emulator-data --export-on-exit=./emulator-data
}

# Get current project info
function fbinfo() {
    echo "Current Firebase Project:"
    firebase use
    echo ""
    echo "Project Details:"
    firebase projects:list 2>/dev/null | grep -E "^\*|Project ID"
    echo ""
    echo "Configured Services:"
    [[ -f "firebase.json" ]] && cat firebase.json | grep -E '"hosting"|"functions"|"firestore"|"database"|"storage"' | head -10
}

# Setup Firebase for Flutter project
function fbflutter() {
    echo "Setting up Firebase for Flutter..."
    echo "Make sure you have FlutterFire CLI installed: dart pub global activate flutterfire_cli"
    echo ""
    flutterfire configure
}

# Setup Firebase for React Native
function fbreactnative() {
    echo "Setting up Firebase for React Native..."
    echo ""
    echo "1. Install packages:"
    echo "   npm install @react-native-firebase/app"
    echo ""
    echo "2. For iOS, add to Podfile and run:"
    echo "   cd ios && pod install"
    echo ""
    echo "3. Download google-services.json (Android) and GoogleService-Info.plist (iOS)"
    echo "   from Firebase Console"
    echo ""
    firebase apps:list
}

# Create new Firebase project
function fbnewproject() {
    if [[ -z "$1" ]]; then
        echo "Usage: fbnewproject <project_name>"
        return 1
    fi
    firebase projects:create "$1"
    firebase use "$1"
    firebase init
}
