# Flutter/Dart Development Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# ===== Flutter Core Commands =====
alias fl='flutter'
alias flv='flutter --version'
alias fldoc='flutter doctor'
alias fldocv='flutter doctor -v'
alias flup='flutter upgrade'
alias flch='flutter channel'
alias flchb='flutter channel beta'
alias flchs='flutter channel stable'
alias flclean='flutter clean'

# ===== Project Management =====
alias flcreate='flutter create'
alias flcreateapp='flutter create --template=app'
alias flcreatepkg='flutter create --template=package'
alias flcreateplugin='flutter create --template=plugin'

# ===== Dependencies (pub) =====
alias flpub='flutter pub'
alias flget='flutter pub get'
alias fladd='flutter pub add'
alias fladdd='flutter pub add --dev'
alias flrm='flutter pub remove'
alias flpubup='flutter pub upgrade'
alias flpubout='flutter pub outdated'
alias flpubdeps='flutter pub deps'
alias flpubcache='flutter pub cache repair'

# ===== Run & Debug =====
alias flrun='flutter run'
alias flrund='flutter run --debug'
alias flrunr='flutter run --release'
alias flrunp='flutter run --profile'
alias flrunw='flutter run -d chrome'
alias flrunm='flutter run -d macos'
alias flrunl='flutter run -d linux'
alias flrunwin='flutter run -d windows'
alias flhot='flutter run --hot'
alias flattach='flutter attach'
alias fllogs='flutter logs'

# ===== Build Commands =====
alias flbuild='flutter build'
alias flbapk='flutter build apk'
alias flbapkr='flutter build apk --release'
alias flbapkd='flutter build apk --debug'
alias flbapksplit='flutter build apk --split-per-abi'
alias flbaab='flutter build appbundle'
alias flbaabr='flutter build appbundle --release'
alias flbios='flutter build ios'
alias flbiosr='flutter build ios --release'
alias flbipa='flutter build ipa'
alias flbipar='flutter build ipa --release'
alias flbweb='flutter build web'
alias flbwebr='flutter build web --release'
alias flbmacos='flutter build macos'
alias flblinux='flutter build linux'
alias flbwin='flutter build windows'

# ===== Testing =====
alias fltest='flutter test'
alias fltestc='flutter test --coverage'
alias fltestv='flutter test --verbose'
alias fltestw='flutter test --watch'
alias flitest='flutter test integration_test'
alias fldtest='flutter drive'

# ===== Code Generation & Analysis =====
alias flanalyze='flutter analyze'
alias flformat='dart format .'
alias flfix='dart fix --apply'
alias flgen='flutter pub run build_runner build'
alias flgenw='flutter pub run build_runner watch'
alias flgend='flutter pub run build_runner build --delete-conflicting-outputs'

# ===== Device Management =====
alias fldevices='flutter devices'
alias flemus='flutter emulators'
alias flemulaunch='flutter emulators --launch'
alias flconfig='flutter config'
alias flconfigweb='flutter config --enable-web'
alias flconfigmacos='flutter config --enable-macos-desktop'
alias flconfiglinux='flutter config --enable-linux-desktop'
alias flconfigwin='flutter config --enable-windows-desktop'

# ===== Dart Specific =====
alias dart='dart'
alias dartv='dart --version'
alias dartrun='dart run'
alias dartcomp='dart compile'
alias dartexe='dart compile exe'
alias dartaot='dart compile aot-snapshot'
alias dartanalyze='dart analyze'
alias dartfix='dart fix'
alias dartfmt='dart format'
alias darttest='dart test'
alias dartpub='dart pub'
alias dartpubget='dart pub get'

# ===== Useful Functions =====

# Create new Flutter project with recommended structure
function flnew() {
    if [[ -z "$1" ]]; then
        echo "Usage: flnew <project_name> [--org com.example]"
        return 1
    fi
    flutter create --template=app --platforms=ios,android,web "$@"
    cd "$1" && flutter pub get
}

# Run on specific device by partial name match
function flrund() {
    if [[ -z "$1" ]]; then
        echo "Usage: flrund <device_name_pattern>"
        flutter devices
        return 1
    fi
    local device=$(flutter devices | grep -i "$1" | head -1 | awk '{print $2}')
    if [[ -n "$device" ]]; then
        flutter run -d "$device"
    else
        echo "Device matching '$1' not found"
        flutter devices
    fi
}

# Clean rebuild
function flrebuild() {
    flutter clean && flutter pub get && flutter run
}

# Full project reset (clean + get + gen)
function flreset() {
    flutter clean
    flutter pub get
    if [[ -f "build.yaml" ]] || grep -q "build_runner" pubspec.yaml 2>/dev/null; then
        flutter pub run build_runner build --delete-conflicting-outputs
    fi
}

# Build release APK and show location
function flrelease() {
    flutter build apk --release && \
    echo "\n APK location: build/app/outputs/flutter-apk/app-release.apk"
}

# Run Flutter web with specific port
function flwebport() {
    local port="${1:-8080}"
    flutter run -d chrome --web-port="$port"
}
