# Google Cloud CLI Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Auth & config
alias gc-auth='gcloud auth login'
alias gc-authlist='gcloud auth list'
alias gc-config='gcloud config list'
alias gc-project='gcloud config get-value project'
alias gc-projects='gcloud projects list'

# Project switching
gc-use() {
    gcloud config set project "$1"
    echo "Switched to project: $1"
}

# Compute Engine
alias gc-vms='gcloud compute instances list'
alias gc-ssh='gcloud compute ssh'
alias gc-scp='gcloud compute scp'
alias gc-zones='gcloud compute zones list'
alias gc-regions='gcloud compute regions list'

# Kubernetes Engine
alias gc-clusters='gcloud container clusters list'
alias gc-getcreds='gcloud container clusters get-credentials'

# Cloud Storage
alias gc-buckets='gsutil ls'
alias gc-cp='gsutil cp'
alias gc-mv='gsutil mv'
alias gc-rm='gsutil rm'
alias gc-rsync='gsutil rsync'

# Cloud Functions
alias gc-functions='gcloud functions list'
alias gc-logs='gcloud functions logs read'

# Cloud Run
alias gc-run='gcloud run services list'
alias gc-deploy='gcloud run deploy'

# IAM
alias gc-iam='gcloud iam service-accounts list'

# Billing
alias gc-billing='gcloud billing accounts list'

# Info
alias gc-info='gcloud info'
alias gc-version='gcloud version'
