# Git Extras Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Stash shortcuts
alias gst='git stash'
alias gstp='git stash pop'
alias gstl='git stash list'
alias gsta='git stash apply'
alias gstd='git stash drop'
alias gstc='git stash clear'
alias gsts='git stash show -p'

# Rebase shortcuts
alias grb='git rebase'
alias grbi='git rebase -i'
alias grbc='git rebase --continue'
alias grba='git rebase --abort'
alias grbs='git rebase --skip'
alias grbm='git rebase main'
alias grbd='git rebase develop'

# Cherry-pick
alias gcp='git cherry-pick'
alias gcpc='git cherry-pick --continue'
alias gcpa='git cherry-pick --abort'

# Reset shortcuts
alias grh='git reset HEAD'
alias grhh='git reset HEAD --hard'
alias grhs='git reset HEAD --soft'
alias gundo='git reset HEAD~1 --soft'

# Branch management
alias gbd='git branch -d'
alias gbD='git branch -D'
alias gbm='git branch -m'
alias gprune='git remote prune origin'
alias gbclean='git branch --merged | grep -v "\*\|main\|master\|develop" | xargs -n 1 git branch -d'

# Log shortcuts
alias glog='git log --oneline --graph --decorate'
alias gloga='git log --oneline --graph --decorate --all'
alias glogp='git log -p'
alias glast='git log -1 HEAD --stat'

# Diff shortcuts
alias gd='git diff'
alias gds='git diff --staged'
alias gdw='git diff --word-diff'

# Commit shortcuts
alias gc='git commit'
alias gcm='git commit -m'
alias gca='git commit --amend'
alias gcan='git commit --amend --no-edit'
alias gcf='git commit --fixup'

# Quick sync
alias gsync='git fetch origin && git rebase origin/$(git branch --show-current)'
alias gpull='git pull --rebase'

# Worktree
alias gwt='git worktree'
alias gwtl='git worktree list'
alias gwta='git worktree add'
alias gwtr='git worktree remove'
