# Golang Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Go environment
export GOPATH="${GOPATH:-$HOME/go}"
export PATH="$PATH:$GOPATH/bin"

# Go shortcuts
alias gob='go build'
alias gor='go run'
alias got='go test'
alias gotv='go test -v'
alias gof='go fmt ./...'
alias gol='golint ./...'
alias govet='go vet ./...'
alias gomod='go mod tidy'
alias goinit='go mod init'
alias goget='go get'
alias godoc='go doc'

# Go build shortcuts
alias gobuild='go build -o bin/'
alias goinstall='go install'
alias goclean='go clean'

# Go test with coverage
alias gotcov='go test -coverprofile=coverage.out && go tool cover -html=coverage.out'
