# History Search Enhancements (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# History settings
export HISTSIZE=50000
export SAVEHIST=50000
export HISTFILE=~/.zsh_history

setopt HIST_IGNORE_ALL_DUPS
setopt HIST_FIND_NO_DUPS
setopt HIST_SAVE_NO_DUPS
setopt SHARE_HISTORY
setopt EXTENDED_HISTORY
setopt INC_APPEND_HISTORY

# Basic history aliases
alias h='history'
alias hl='history | tail -50'
alias hg='history | grep'
alias hc='history -c && rm -f ~/.zsh_history'

# FZF history search (if fzf is installed)
if command -v fzf &> /dev/null; then
    fh() {
        local cmd=$(history | fzf --tac --no-sort | sed 's/^[ ]*[0-9]*[ ]*//')
        if [[ -n "$cmd" ]]; then
            print -z "$cmd"
        fi
    }
    
    # Ctrl+R replacement with fzf
    fzf-history-widget() {
        local selected=$(fc -rl 1 | fzf --tac --no-sort -q "$LBUFFER" | sed 's/^[ ]*[0-9]*[ ]*//')
        if [[ -n "$selected" ]]; then
            BUFFER="$selected"
            CURSOR=$#BUFFER
        fi
        zle redisplay
    }
    zle -N fzf-history-widget
    bindkey '^R' fzf-history-widget
fi

# History stats
alias htop10='history | awk '\''{print $2}'\'' | sort | uniq -c | sort -rn | head -10'

# Search and run from history
hr() {
    local cmd=$(history | grep "$1" | tail -1 | sed 's/^[ ]*[0-9]*[ ]*//')
    if [[ -n "$cmd" ]]; then
        echo "Running: $cmd"
        eval "$cmd"
    else
        echo "No match found for: $1"
    fi
}
