# Java/Maven/Gradle Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Java version switching (macOS with jenv or /usr/libexec/java_home)
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias java8='export JAVA_HOME=$(/usr/libexec/java_home -v 1.8)'
    alias java11='export JAVA_HOME=$(/usr/libexec/java_home -v 11)'
    alias java17='export JAVA_HOME=$(/usr/libexec/java_home -v 17)'
    alias java21='export JAVA_HOME=$(/usr/libexec/java_home -v 21)'
    alias java-list='/usr/libexec/java_home -V'
fi

# Java shortcuts
alias jv='java -version'
alias jc='javac'

# Maven shortcuts
alias mvn='mvn'
alias mci='mvn clean install'
alias mcis='mvn clean install -DskipTests'
alias mcp='mvn clean package'
alias mcps='mvn clean package -DskipTests'
alias mt='mvn test'
alias mc='mvn clean'
alias mcc='mvn compile'
alias mdeps='mvn dependency:tree'
alias mver='mvn versions:display-dependency-updates'

# Gradle shortcuts
alias gw='./gradlew'
alias gwb='./gradlew build'
alias gwc='./gradlew clean'
alias gwcb='./gradlew clean build'
alias gwt='./gradlew test'
alias gwr='./gradlew run'
alias gwdeps='./gradlew dependencies'
alias gwboot='./gradlew bootRun'

# Spring Boot
alias sbr='mvn spring-boot:run'
alias sbrd='mvn spring-boot:run -Dspring-boot.run.profiles=dev'
