# Kubernetes Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Context & namespace management
alias kctx='kubectl config get-contexts'
alias kuse='kubectl config use-context'
alias kns='kubectl config set-context --current --namespace'
alias kcurrent='kubectl config current-context'

# Pod management
alias kgp='kubectl get pods'
alias kgpa='kubectl get pods --all-namespaces'
alias kgpw='kubectl get pods -o wide'
alias kdp='kubectl describe pod'
alias kdelp='kubectl delete pod'
alias klogs='kubectl logs'
alias klogsf='kubectl logs -f'
alias kexec='kubectl exec -it'

# Deployments
alias kgd='kubectl get deployments'
alias kdd='kubectl describe deployment'
alias ksd='kubectl scale deployment'
alias krd='kubectl rollout restart deployment'

# Services & ingress
alias kgs='kubectl get services'
alias kgi='kubectl get ingress'
alias kgn='kubectl get nodes'

# Apply & delete
alias ka='kubectl apply -f'
alias kd='kubectl delete -f'
alias kdel='kubectl delete'

# Get all resources
alias kga='kubectl get all'
alias kgaa='kubectl get all --all-namespaces'

# Port forwarding
alias kpf='kubectl port-forward'

# Quick shell into pod
kshell() {
    kubectl exec -it "$1" -- /bin/sh
}

kbash() {
    kubectl exec -it "$1" -- /bin/bash
}
