# Memcached Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Memcached service management
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias memcached-start='brew services start memcached'
    alias memcached-stop='brew services stop memcached'
    alias memcached-restart='brew services restart memcached'
    alias memcached-status='brew services info memcached'
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    alias memcached-start='sudo systemctl start memcached'
    alias memcached-stop='sudo systemctl stop memcached'
    alias memcached-restart='sudo systemctl restart memcached'
    alias memcached-status='systemctl status memcached'
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    alias memcached-start='net start memcached'
    alias memcached-stop='net stop memcached'
    alias memcached-restart='net stop memcached & net start memcached'
    alias memcached-status='sc query memcached'
fi

# Memcached shortcuts
alias mc-stats='echo "stats" | nc localhost 11211'
alias mc-flush='echo "flush_all" | nc localhost 11211'
alias mc-version='echo "version" | nc localhost 11211'
