# MongoDB Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# MongoDB service management
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias mongo-start='brew services start mongodb-community'
    alias mongo-stop='brew services stop mongodb-community'
    alias mongo-restart='brew services restart mongodb-community'
    alias mongo-status='brew services info mongodb-community'
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    alias mongo-start='sudo systemctl start mongod'
    alias mongo-stop='sudo systemctl stop mongod'
    alias mongo-restart='sudo systemctl restart mongod'
    alias mongo-status='systemctl status mongod'
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    alias mongo-start='net start MongoDB'
    alias mongo-stop='net stop MongoDB'
    alias mongo-restart='net stop MongoDB & net start MongoDB'
    alias mongo-status='sc query MongoDB'
fi

# MongoDB shell shortcuts (cross-platform)
alias mongosh='mongosh --quiet'
alias mongo-local='mongosh mongodb://localhost:27017'
