# MySQL Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# MySQL service management
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias mysql-start='brew services start mysql'
    alias mysql-stop='brew services stop mysql'
    alias mysql-restart='brew services restart mysql'
    alias mysql-status='brew services info mysql'
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    alias mysql-start='sudo systemctl start mysql'
    alias mysql-stop='sudo systemctl stop mysql'
    alias mysql-restart='sudo systemctl restart mysql'
    alias mysql-status='systemctl status mysql'
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    alias mysql-start='net start MySQL'
    alias mysql-stop='net stop MySQL'
    alias mysql-restart='net stop MySQL & net start MySQL'
    alias mysql-status='sc query MySQL'
fi

# MySQL shell shortcuts (cross-platform)
alias mysql-local='mysql -h localhost -u root'
alias mysql-secure='mysql_secure_installation'
