# Node.js/NPM/Yarn/PNPM Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# NPM shortcuts
alias ni='npm install'
alias nid='npm install --save-dev'
alias nig='npm install -g'
alias nu='npm uninstall'
alias nup='npm update'
alias nr='npm run'
alias nrs='npm run start'
alias nrd='npm run dev'
alias nrb='npm run build'
alias nrt='npm run test'
alias nrl='npm run lint'
alias npx='npx'
alias nci='npm ci'
alias nau='npm audit'
alias nauf='npm audit fix'

# Yarn shortcuts
alias yi='yarn install'
alias ya='yarn add'
alias yad='yarn add --dev'
alias yr='yarn remove'
alias yrs='yarn start'
alias yrd='yarn dev'
alias yrb='yarn build'
alias yrt='yarn test'
alias yrl='yarn lint'
alias yu='yarn upgrade'
alias yui='yarn upgrade-interactive'

# PNPM shortcuts
alias pi='pnpm install'
alias pa='pnpm add'
alias pad='pnpm add -D'
alias pr='pnpm remove'
alias prs='pnpm start'
alias prd='pnpm dev'
alias prb='pnpm build'
alias prt='pnpm test'

# NVM shortcuts
alias nvmi='nvm install'
alias nvmu='nvm use'
alias nvml='nvm list'
alias nvmlr='nvm list-remote'
alias nvmd='nvm alias default'
alias nvmc='nvm current'

# Node shortcuts
alias node-v='node --version'
alias npm-v='npm --version'
