# PostgreSQL Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# PostgreSQL service management
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias pg-start='brew services start postgresql@14'
    alias pg-stop='brew services stop postgresql@14'
    alias pg-restart='brew services restart postgresql@14'
    alias pg-status='brew services info postgresql@14'
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    alias pg-start='sudo systemctl start postgresql'
    alias pg-stop='sudo systemctl stop postgresql'
    alias pg-restart='sudo systemctl restart postgresql'
    alias pg-status='systemctl status postgresql'
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    alias pg-start='net start postgresql-x64-14'
    alias pg-stop='net stop postgresql-x64-14'
    alias pg-restart='net stop postgresql-x64-14 & net start postgresql-x64-14'
    alias pg-status='sc query postgresql-x64-14'
fi

# PostgreSQL shell shortcuts (cross-platform)
alias pg-local='psql -h localhost -U postgres'
alias pg-list='psql -l'
alias pg-createdb='createdb'
alias pg-dropdb='dropdb'
