# Python Virtual Environment Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Virtual environment creation
alias venv-create='python3 -m venv venv'
alias venv-create-name='python3 -m venv'

# Virtual environment activation (cross-platform)
venv-activate() {
    local venv_dir="${1:-venv}"
    if [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
        source "$venv_dir/Scripts/activate"
    else
        source "$venv_dir/bin/activate"
    fi
}

alias va='venv-activate'
alias vd='deactivate'

# Pip shortcuts
alias pip-freeze='pip freeze > requirements.txt'
alias pip-install='pip install -r requirements.txt'
alias pip-upgrade='pip install --upgrade pip'
alias pip-list='pip list --outdated'

# Python shortcuts
alias py='python3'
alias py2='python2'
alias ipy='ipython'

# Django shortcuts
alias djrun='python manage.py runserver'
alias djmig='python manage.py migrate'
alias djmake='python manage.py makemigrations'
alias djshell='python manage.py shell'
