# RabbitMQ Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# RabbitMQ service management
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias rabbitmq-start='brew services start rabbitmq'
    alias rabbitmq-stop='brew services stop rabbitmq'
    alias rabbitmq-restart='brew services restart rabbitmq'
    alias rabbitmq-status='brew services info rabbitmq'
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    alias rabbitmq-start='sudo systemctl start rabbitmq-server'
    alias rabbitmq-stop='sudo systemctl stop rabbitmq-server'
    alias rabbitmq-restart='sudo systemctl restart rabbitmq-server'
    alias rabbitmq-status='systemctl status rabbitmq-server'
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    alias rabbitmq-start='net start RabbitMQ'
    alias rabbitmq-stop='net stop RabbitMQ'
    alias rabbitmq-restart='net stop RabbitMQ & net start RabbitMQ'
    alias rabbitmq-status='sc query RabbitMQ'
fi

# RabbitMQ management shortcuts (cross-platform)
alias rabbitmq-plugins='rabbitmq-plugins list'
alias rabbitmq-enable-mgmt='rabbitmq-plugins enable rabbitmq_management'
alias rabbitmq-users='rabbitmqctl list_users'
alias rabbitmq-vhosts='rabbitmqctl list_vhosts'
alias rabbitmq-queues='rabbitmqctl list_queues'
alias rabbitmq-exchanges='rabbitmqctl list_exchanges'
