# React Native Development Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# ===== React Native CLI Core =====
alias rn='npx react-native'
alias rnv='npx react-native --version'
alias rninfo='npx react-native info'
alias rndoctor='npx react-native doctor'

# ===== Project Creation =====
alias rninit='npx react-native init'
alias rninitnew='npx @react-native-community/cli init'
alias rncreate='npx create-expo-app'

# ===== Run Commands =====
alias rnstart='npx react-native start'
alias rnstartc='npx react-native start --reset-cache'
alias rnstartr='npx react-native start --reset-cache'
alias rnandroid='npx react-native run-android'
alias rnios='npx react-native run-ios'
alias rniosd='npx react-native run-ios --device'
alias rniossim='npx react-native run-ios --simulator'
alias rnweb='npx react-native start --web'

# ===== Build Commands =====
alias rnbanda='cd android && ./gradlew assembleDebug && cd ..'
alias rnbandar='cd android && ./gradlew assembleRelease && cd ..'
alias rnbbundle='cd android && ./gradlew bundleRelease && cd ..'
alias rnbios='xcodebuild -workspace ios/*.xcworkspace -scheme App -configuration Release'
alias rnarchive='xcodebuild -workspace ios/*.xcworkspace -scheme App archive'

# ===== Metro Bundler =====
alias rnmetro='npx react-native start'
alias rnmetroc='npx react-native start --reset-cache'
alias rnbundle='npx react-native bundle'
alias rnbundleand='npx react-native bundle --platform android --dev false --entry-file index.js --bundle-output android/app/src/main/assets/index.android.bundle'
alias rnbundleios='npx react-native bundle --platform ios --dev false --entry-file index.js --bundle-output ios/main.jsbundle'

# ===== Debugging =====
alias rnlog='npx react-native log-android'
alias rnlogios='npx react-native log-ios'
alias rnshake='adb shell input keyevent 82'
alias rndevmenu='adb shell input keyevent 82'
alias rnreload='adb shell input text "RR"'
alias rnremotedebug='adb reverse tcp:8081 tcp:8081'

# ===== Android Specific =====
alias rnadbr='adb reverse tcp:8081 tcp:8081'
alias rngradle='cd android && ./gradlew'
alias rngradlec='cd android && ./gradlew clean && cd ..'
alias rngradled='cd android && ./gradlew assembleDebug && cd ..'
alias rngradler='cd android && ./gradlew assembleRelease && cd ..'
alias rngradlew='cd android && ./gradlew wrapper && cd ..'
alias rnandclean='cd android && ./gradlew clean && cd ..'
alias rnapk='cd android && ./gradlew assembleRelease && cd .. && echo "\n APK: android/app/build/outputs/apk/release/"'
alias rnaab='cd android && ./gradlew bundleRelease && cd .. && echo "\n AAB: android/app/build/outputs/bundle/release/"'

# ===== iOS Specific =====
alias rnpod='cd ios && pod install && cd ..'
alias rnpodupdate='cd ios && pod update && cd ..'
alias rnpodclean='cd ios && pod deintegrate && pod install && cd ..'
alias rnpodrepo='cd ios && pod repo update && cd ..'
alias rnxcode='open ios/*.xcworkspace'
alias rnxcodeclean='xcodebuild clean -workspace ios/*.xcworkspace -scheme App'
alias rnsimlist='xcrun simctl list devices'
alias rnsimboot='xcrun simctl boot'
alias rnsimopen='open -a Simulator'

# ===== Dependencies =====
alias rnnpm='npm install'
alias rnyarn='yarn install'
alias rnlink='npx react-native link'
alias rnunlink='npx react-native unlink'
alias rnpodlink='cd ios && pod install && cd ..'

# ===== Cache & Clean =====
alias rnclean='rm -rf node_modules && npm install'
alias rncleany='rm -rf node_modules && yarn install'
alias rnwatchman='watchman watch-del-all'
alias rncache='npm start -- --reset-cache'
alias rnfullclean='watchman watch-del-all && rm -rf node_modules && rm -rf $TMPDIR/react-* && rm -rf $TMPDIR/metro-* && npm install'
alias rndeepclean='watchman watch-del-all && rm -rf node_modules && rm -rf ios/Pods && rm -rf ios/build && rm -rf android/build && rm -rf android/app/build && npm install && cd ios && pod install && cd ..'

# ===== Testing =====
alias rntest='npm test'
alias rntestw='npm test -- --watch'
alias rntestc='npm test -- --coverage'
alias rnjest='npx jest'
alias rnjestw='npx jest --watch'
alias rndetox='npx detox'
alias rndetoxb='npx detox build'
alias rndetoxr='npx detox test'

# ===== Expo (for Expo projects) =====
alias expo='npx expo'
alias expostart='npx expo start'
alias expostartc='npx expo start --clear'
alias expoand='npx expo start --android'
alias expoios='npx expo start --ios'
alias expoweb='npx expo start --web'
alias expobuild='npx expo build'
alias expobuilda='npx expo build:android'
alias expobuildi='npx expo build:ios'
alias expopub='npx expo publish'
alias expoexport='npx expo export'
alias expoinstall='npx expo install'
alias expodr='npx expo doctor'
alias expoupgrade='npx expo upgrade'
alias expoenv='npx expo env:info'
alias expoeject='npx expo eject'

# ===== EAS (Expo Application Services) =====
alias eas='npx eas-cli'
alias easbuild='npx eas-cli build'
alias easbuilda='npx eas-cli build --platform android'
alias easbuildi='npx eas-cli build --platform ios'
alias easbuildall='npx eas-cli build --platform all'
alias eassubmit='npx eas-cli submit'
alias eassubmita='npx eas-cli submit --platform android'
alias eassubmiti='npx eas-cli submit --platform ios'
alias easupdate='npx eas-cli update'
alias easdevice='npx eas-cli device:create'

# ===== Useful Functions =====

# Create new React Native project with TypeScript
function rnnew() {
    if [[ -z "$1" ]]; then
        echo "Usage: rnnew <project_name>"
        return 1
    fi
    npx react-native init "$1" --template react-native-template-typescript
    cd "$1"
}

# Create new Expo project
function exponew() {
    if [[ -z "$1" ]]; then
        echo "Usage: exponew <project_name>"
        return 1
    fi
    npx create-expo-app "$1" --template expo-template-blank-typescript
    cd "$1"
}

# Full clean and reinstall
function rnreset() {
    echo "Cleaning React Native project..."
    watchman watch-del-all 2>/dev/null || true
    rm -rf node_modules
    rm -rf ios/Pods ios/build
    rm -rf android/build android/app/build
    rm -rf $TMPDIR/react-* $TMPDIR/metro-* $TMPDIR/haste-*
    echo "Installing dependencies..."
    npm install
    if [[ -d "ios" ]]; then
        echo "Installing pods..."
        cd ios && pod install && cd ..
    fi
    echo "Done! Run 'rnstart' to start Metro."
}

# Run on specific Android device/emulator
function rnanddev() {
    local devices=$(adb devices | grep -v "List" | grep "device$" | awk '{print $1}')
    if [[ -z "$devices" ]]; then
        echo "No Android devices found"
        return 1
    fi
    echo "Available devices:"
    echo "$devices"
    if [[ -n "$1" ]]; then
        npx react-native run-android --deviceId "$1"
    else
        npx react-native run-android
    fi
}

# Run on specific iOS simulator
function rniossimname() {
    if [[ -z "$1" ]]; then
        echo "Usage: rniossimname <simulator_name>"
        echo "Available simulators:"
        xcrun simctl list devices available | grep -E "iPhone|iPad"
        return 1
    fi
    npx react-native run-ios --simulator="$1"
}

# Open React Native debugger
function rndebugger() {
    open "rndebugger://set-debugger-loc?host=localhost&port=8081"
}

# Generate release APK and show path
function rnreleaseapk() {
    echo "Building release APK..."
    cd android && ./gradlew assembleRelease && cd ..
    local apk_path="android/app/build/outputs/apk/release/app-release.apk"
    if [[ -f "$apk_path" ]]; then
        echo "\n Release APK: $apk_path"
        ls -lh "$apk_path"
    fi
}

# Reverse ports for debugging
function rnports() {
    adb reverse tcp:8081 tcp:8081
    adb reverse tcp:8097 tcp:8097
    echo "Ports reversed: 8081 (Metro), 8097 (React DevTools)"
}
