# Redis Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Redis service management
if [[ "$OSTYPE" == "darwin"* ]]; then
    alias redis-start='brew services start redis'
    alias redis-stop='brew services stop redis'
    alias redis-restart='brew services restart redis'
    alias redis-status='brew services info redis'
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    alias redis-start='sudo systemctl start redis-server'
    alias redis-stop='sudo systemctl stop redis-server'
    alias redis-restart='sudo systemctl restart redis-server'
    alias redis-status='systemctl status redis-server'
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    alias redis-start='net start Redis'
    alias redis-stop='net stop Redis'
    alias redis-restart='net stop Redis & net start Redis'
    alias redis-status='sc query Redis'
fi

# Redis CLI shortcuts (cross-platform)
alias redis-local='redis-cli -h localhost -p 6379'
alias redis-ping='redis-cli ping'
alias redis-flush='redis-cli flushall'
