# Rust/Cargo Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Rust environment
export PATH="$PATH:$HOME/.cargo/bin"

# Cargo shortcuts
alias cb='cargo build'
alias cbr='cargo build --release'
alias cr='cargo run'
alias crr='cargo run --release'
alias ct='cargo test'
alias ctv='cargo test -- --nocapture'
alias cc='cargo check'
alias cf='cargo fmt'
alias cl='cargo clippy'
alias cdoc='cargo doc --open'
alias cupdate='cargo update'
alias cclean='cargo clean'

# Cargo new project
alias cnew='cargo new'
alias cinit='cargo init'

# Rustup shortcuts
alias rupdate='rustup update'
alias rdefault='rustup default'
alias rtarget='rustup target add'
