# Service Management Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Detect OS and set appropriate commands
if [[ "$OSTYPE" == "darwin"* ]]; then
    # macOS (Homebrew)
    alias svc-list='brew services list'
    alias svc-start='brew services start'
    alias svc-stop='brew services stop'
    alias svc-restart='brew services restart'
    alias svc-info='brew services info'
elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
    # Linux (systemd)
    alias svc-list='systemctl list-units --type=service'
    alias svc-start='sudo systemctl start'
    alias svc-stop='sudo systemctl stop'
    alias svc-restart='sudo systemctl restart'
    alias svc-info='systemctl status'
elif [[ "$OSTYPE" == "msys" ]] || [[ "$OSTYPE" == "cygwin" ]]; then
    # Windows (Git Bash/Cygwin)
    alias svc-list='sc query type= service state= all'
    alias svc-start='net start'
    alias svc-stop='net stop'
    alias svc-restart='echo "Use svc-stop then svc-start"'
    alias svc-info='sc query'
fi
