# SSH Manager Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# SSH key management
alias ssh-list='ls -la ~/.ssh/'
alias ssh-config='cat ~/.ssh/config'
alias ssh-edit='${EDITOR:-nano} ~/.ssh/config'

# SSH key generation
ssh-keygen-ed() {
    local name="${1:-id_ed25519}"
    ssh-keygen -t ed25519 -C "${2:-$(whoami)@$(hostname)}" -f ~/.ssh/"$name"
}

ssh-keygen-rsa() {
    local name="${1:-id_rsa}"
    ssh-keygen -t rsa -b 4096 -C "${2:-$(whoami)@$(hostname)}" -f ~/.ssh/"$name"
}

# SSH agent management
alias ssh-agent-start='eval "$(ssh-agent -s)"'
alias ssh-add-default='ssh-add ~/.ssh/id_ed25519 2>/dev/null || ssh-add ~/.ssh/id_rsa'
alias ssh-add-all='find ~/.ssh -name "id_*" ! -name "*.pub" -exec ssh-add {} \;'

# SSH copy public key
ssh-copy-key() {
    local key="${1:-~/.ssh/id_ed25519.pub}"
    if [[ -f "$key" ]]; then
        cat "$key" | pbcopy 2>/dev/null || cat "$key" | xclip -selection clipboard 2>/dev/null || cat "$key"
        echo "Public key copied to clipboard (or printed above)"
    else
        echo "Key not found: $key"
    fi
}

# SSH test connection
alias ssh-test='ssh -T git@github.com'
