# Terraform Aliases (Cross-platform)
# Auto-generated by awesome-lazy-zsh

# Core commands
alias tfi='terraform init'
alias tfp='terraform plan'
alias tfa='terraform apply'
alias tfaa='terraform apply -auto-approve'
alias tfd='terraform destroy'
alias tfda='terraform destroy -auto-approve'
alias tfv='terraform validate'
alias tff='terraform fmt'
alias tffr='terraform fmt -recursive'

# State management
alias tfs='terraform state'
alias tfsl='terraform state list'
alias tfss='terraform state show'
alias tfsm='terraform state mv'
alias tfsr='terraform state rm'

# Workspace management
alias tfw='terraform workspace'
alias tfwl='terraform workspace list'
alias tfws='terraform workspace select'
alias tfwn='terraform workspace new'
alias tfwd='terraform workspace delete'

# Output & console
alias tfo='terraform output'
alias tfoj='terraform output -json'
alias tfc='terraform console'

# Graph & providers
alias tfg='terraform graph'
alias tfproviders='terraform providers'

# Plan with output file
tfplan() {
    terraform plan -out="${1:-tfplan}"
}

tfapplyplan() {
    terraform apply "${1:-tfplan}"
}
