name: Update Homebrew Formula

on:
  release:
    types: [published]

jobs:
  update-homebrew:
    runs-on: ubuntu-latest
    steps:
      - name: Update Homebrew formula
        uses: mislav/bump-homebrew-formula-action@v3.6
        with:
          formula-name: awesome-lazy-zsh
          homebrew-tap: AmJaradat01/homebrew-awesome-lazy-zsh
          download-url: https://github.com/AmJaradat01/awesome-lazy-zsh/archive/refs/tags/${{ github.event.release.tag_name }}.tar.gz
        env:
          COMMITTER_TOKEN: ${{ secrets.HOMEBREW_TAP_TOKEN }}
